### ISSUE TITLE
Getting 400 Bad Request on health checks / http requests

### ISSUE THREAD

**Issue by DjangoFett** [FINRAOS/aphelion#19]
I'm attempting to deploy using ECS and an ALB. Everything has turned on with seemingly no problem, however I'm getting http error on my health checks from the ALB and http requests from the browser.

**Comment by HurielHernandez** [comment]
Hello there. What URL are you specifying for health checks?  We provide /datapoints/health endpoint that you can use to set the healthy check url.

**Comment by DjangoFett** [comment]
I was initially using "/", but it doesn't seem to be giving me any other results using "/datapoints/health".
`"GET /datapoints/health HTTP/1.1" 400 272 "-" "ELB-HealthChecker/2.0"`

**Comment by DjangoFett** [comment]
I found my issue: I was sending the health check to port 80 instead of 443. This was preventing the ECS service from hitting a steady state. Once I switched the health check to port 443 it stabilized and was reachable. 

Is there some sort of forum or chat application we can use. It didn't feel like an issue, but I didn't see any other means of communications?

Thanks for the help!

**Comment by HurielHernandez** [comment]
I'm glad you found the problem.  Thanks for updating us on the issue and solution.

**Comment by kood1** [comment]
@DjangoFett - We can continue to use GitHub issues for communicating any issues you face.  We may look for other forums in the future.
