### ISSUE TITLE
dockerfile referencing JAR file that is missing

### ISSUE THREAD

**Issue by JohnTheodore** [FINRAOS/aphelion#6]
"ADD target/*.jar /opt/staging" <- this line from Dockerfile.. what jar file is this? Is there a way I can just download/compile this myself?

**Comment by HurielHernandez** [comment]
The Dockerfile "ADD target/*.jar" line refers to the compiled jar file by the Spring Boot application.  In that folder you can run `mvn clean install` to generate to compile the application and generate the folder and *.jar file.  Note that you need to have Maven installed on your machine to compile the application.

**Comment by kood1** [comment]
@JohnTheodore - We are setting up CI for this project so we will have a script that builds all the code and run docker to create the images.  The script will include the necessary builds including mvn.  For now, as @HurielHernandez mentioned above, you can run maven install to create the jar files in target directory then run docker to create the image.
